version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis-mmf
    networks:
      # - d2api_default
      - mmf_network
    ports:
      - "6378:6379"
    restart: always

  mmf:
    build: ../
    image: relative-fi/mmf
    container_name: mmf
    restart: always
    env_file:
      - ../.env
    networks:
      - mmf_network
    ports:
      - "9876:9876"
    depends_on:
      - redis
    command: go run ./cmd/main.go
    develop:
      watch:
        - action: sync+restart
          path: ../
          target: /app

networks:
  mmf_network:
    driver: bridge
